// ─── Mock Data – Products, Categories, Offers, Orders ────────────────────────
// Built from the Hafsum Coffee & Cake trifold menu (front + back).
// Prices are in PKR. Replace BASE_URL with your real API once the backend is ready.

export const BASE_URL = 'https://api.hafsum.com/v1';  // ← swap to real URL

// ─── Categories ──────────────────────────────────────────────────────────────
export const CATEGORIES = [
  { id: 'all',              name: 'All',                icon: '🍽️' },
  { id: 'cakes',             name: 'Premium Cakes',      icon: '🎂' },
  { id: 'cheesecakes',       name: 'Cheesecakes',        icon: '🍰' },
  { id: 'specialty-cakes',   name: 'Specialty Cakes',    icon: '🎂' },
  { id: 'classic-cakes',     name: 'Classic Cakes',      icon: '🍰' },
  { id: 'savories',          name: 'Savories',           icon: '🥟' },
  { id: 'pasta',             name: 'Pasta',              icon: '🍝' },
  { id: 'sandwiches',        name: 'Cold Sandwiches',    icon: '🥪' },
  { id: 'pastries-eclairs',  name: 'Pastries & Eclairs', icon: '🥐' },
  { id: 'salads',            name: 'Salads',             icon: '🥗' },
  { id: 'pies-tarts',        name: "Pie's & Tarts",      icon: '🥧' },
  { id: 'bread-croissant',   name: 'Bread & Croissant',  icon: '🍞' },
  { id: 'cupcakes',          name: 'Cupcakes',           icon: '🧁' },
  { id: 'brownies-cookies',  name: 'Brownies & Cookies', icon: '🍪' },
  { id: 'donuts',            name: 'Donuts',             icon: '🍩' },
  { id: 'sundaes',           name: "Sundae's",           icon: '🍨' },
  { id: 'muffins',           name: 'Muffins',            icon: '🧁' },
  { id: 'hot-coffee',        name: 'Hot Coffee',         icon: '☕' },
  { id: 'cold-coffee',       name: 'Cold Coffee',        icon: '🧊' },
  { id: 'mojitos',           name: 'Mojitos',            icon: '🍹' },
  { id: 'lemonades',         name: 'Lemonades',          icon: '🍋' },
  { id: 'iced-teas',         name: 'Iced Teas',          icon: '🧋' },
  { id: 'mocktails',         name: 'Mocktails',          icon: '🍸' },
];

// ─── Products ─────────────────────────────────────────────────────────────────
export const PRODUCTS = [

  // ───────────────────────────── Premium Cakes (1.5lb / 2.5lb) ─────────────────
  { id: 'c01', categoryId: 'cakes', name: 'Tres Leches Cadbury Cake', price: 2199,
    description: 'Soaked three-milk sponge layered with Cadbury chocolate cream — moist, rich and unapologetically indulgent.',
    image: require('../../assets/images/cake_mango.jpg'), popular: true,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 2199 }, { id: '2.5lb', label: '2.5 lb', price: 3200 }], addons: [] },
  { id: 'c02', categoryId: 'cakes', name: 'Tres Leches Lotus Cake', price: 2250,
    description: 'Milk-soaked sponge finished with creamy Lotus Biscoff spread and crushed biscuit crumble.',
    image: require('../../assets/images/cake_lotus_biscoff.jpg'), popular: true,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 2250 }, { id: '2.5lb', label: '2.5 lb', price: 3250 }], addons: [] },
  { id: 'c03', categoryId: 'cakes', name: 'Tres Leches Pistachio Cake', price: 2250,
    description: 'A nutty twist on the classic tres leches, layered with pistachio cream for a delicate, fragrant finish.',
    image: require('../../assets/images/cake_pistachio.jpg'), popular: false,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 2250 }, { id: '2.5lb', label: '2.5 lb', price: 3400 }], addons: [] },
  { id: 'c04', categoryId: 'cakes', name: 'Raffaello White Chocolate Cake', price: 2199,
    description: 'Coconut and almond sponge wrapped in silky white chocolate cream, inspired by the classic Raffaello praline.',
    image: require('../../assets/images/cake_raffaello.jpg'), popular: false,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 2199 }, { id: '2.5lb', label: '2.5 lb', price: 3200 }], addons: [] },
  { id: 'c05', categoryId: 'cakes', name: 'Chocolate Dream Mousse Cake', price: 2250,
    description: 'Airy chocolate mousse layered over a soft cocoa sponge for a light yet deeply chocolatey bite.',
    image: require('../../assets/images/cake_chocolate_mousse.jpg'), popular: false,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 2250 }, { id: '2.5lb', label: '2.5 lb', price: 3200 }], addons: [] },
  { id: 'c06', categoryId: 'cakes', name: 'Three Milk Cake', price: 1999,
    description: 'The original tres leches — sponge soaked in a trio of milks, topped with a light whipped cream.',
    image: require('../../assets/images/cake_snicker_bar.jpg'), popular: false,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 1999 }, { id: '2.5lb', label: '2.5 lb', price: 2999 }], addons: [] },
  { id: 'c07', categoryId: 'cakes', name: 'Snicker Bar Chocolate Cake', price: 1999,
    description: 'Chocolate sponge loaded with caramel, peanuts and chocolate drizzle for a Snickers-inspired treat.',
    image: require('../../assets/images/cake_chocolate_rosette.jpg'), popular: true,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 1999 }, { id: '2.5lb', label: '2.5 lb', price: 3400 }], addons: [] },
  { id: 'c08', categoryId: 'cakes', name: 'Salted Caramel Cake', price: 2199,
    description: 'Buttery caramel cream and a hint of sea salt layered over a soft vanilla-chocolate sponge.',
    image: require('../../assets/images/cake_caramel_coffee.jpg'), popular: false,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 2199 }, { id: '2.5lb', label: '2.5 lb', price: 2999 }], addons: [] },
  { id: 'c09', categoryId: 'cakes', name: 'Belgian Chocolate Cake', price: 2199,
    description: 'Rich Belgian chocolate sponge with layers of dark ganache — intense and velvety.',
    image: require('../../assets/images/cake_dark_chocolate.jpg'), popular: false,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 2199 }, { id: '2.5lb', label: '2.5 lb', price: 3200 }], addons: [] },
  { id: 'c10', categoryId: 'cakes', name: 'Red Velvet Cake', price: 2199,
    description: 'Classic red velvet sponge with a tangy cream cheese frosting between every layer.',
    image: require('../../assets/images/cake_red_velvet.jpg'), popular: true,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 2199 }, { id: '2.5lb', label: '2.5 lb', price: 2999 }], addons: [] },
  { id: 'c11', categoryId: 'cakes', name: 'Chocolate Fudge Cake', price: 1999,
    description: 'Dense, fudgy chocolate sponge layered with thick chocolate fudge frosting.',
    image: require('../../assets/images/cake_chocolate_shavings.jpg'), popular: false,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 1999 }, { id: '2.5lb', label: '2.5 lb', price: 2999 }], addons: [] },
  { id: 'c12', categoryId: 'cakes', name: 'German Fudge Cake', price: 1999,
    description: 'A twist on the classic fudge cake with a slightly darker, more intense cocoa profile.',
    image: require('../../assets/images/cake_sticky_toffee.jpg'), popular: false,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 1999 }, { id: '2.5lb', label: '2.5 lb', price: 2999 }], addons: [] },
  { id: 'c13', categoryId: 'cakes', name: 'Coffee Cake', price: 1999,
    description: 'Light coffee-infused sponge layered with a smooth coffee buttercream.',
    image: require('../../assets/images/cake_coffee.jpg'), popular: false,
    sizes: [{ id: '1.5lb', label: '1.5 lb', price: 1999 }, { id: '2.5lb', label: '2.5 lb', price: 2999 }], addons: [] },

  // ───────────────────────────── Cheesecakes (Slice / 2.5lb) ────────────────────
  { id: 'ch01', categoryId: 'cheesecakes', name: 'Oreo Chocolate Cheesecake', price: 825,
    description: 'Creamy chocolate cheesecake loaded with crushed Oreo cookies on a chocolate biscuit base.',
    image: '', popular: true,
    sizes: [{ id: 'slice', label: 'Slice', price: 825 }, { id: '2.5lb', label: '2.5 lb', price: 6500 }], addons: [] },
  { id: 'ch02', categoryId: 'cheesecakes', name: 'Chocolate Truffle Cheesecake', price: 825,
    description: 'Silky cheesecake topped with a glossy chocolate truffle layer for a decadent finish.',
    image: require('../../assets/images/cake_chocolate_truffle.jpg'), popular: false,
    sizes: [{ id: 'slice', label: 'Slice', price: 825 }, { id: '2.5lb', label: '2.5 lb', price: 6500 }], addons: [] },
  { id: 'ch03', categoryId: 'cheesecakes', name: 'New York Cheesecake', price: 825,
    description: 'The classic dense, creamy New York-style cheesecake on a buttery graham crust.',
    image: '', popular: true,
    sizes: [{ id: 'slice', label: 'Slice', price: 825 }, { id: '2.5lb', label: '2.5 lb', price: 6500 }], addons: [] },
  { id: 'ch04', categoryId: 'cheesecakes', name: 'San Sebastian Cheesecake', price: 825,
    description: 'Basque-style burnt cheesecake with a caramelized top and a soft, almost molten center.',
    image: require('../../assets/images/cake_caramel_cheesecake.jpg'), popular: false,
    sizes: [{ id: 'slice', label: 'Slice', price: 825 }, { id: '2.5lb', label: '2.5 lb', price: 6500 }], addons: [] },
  { id: 'ch05', categoryId: 'cheesecakes', name: 'Blueberry Cheesecake', price: 825,
    description: 'Smooth vanilla cheesecake swirled and topped with a tangy blueberry compote.',
    image: require('../../assets/images/cake_blueberry_cheesecake.jpg'), popular: false,
    sizes: [{ id: 'slice', label: 'Slice', price: 825 }, { id: '2.5lb', label: '2.5 lb', price: 6500 }], addons: [] },

  // ───────────────────────────── Specialty Cakes (2 lb) ─────────────────────────
  { id: 's01', categoryId: 'specialty-cakes', name: 'Roasted Almond Cake', price: 2800,
    description: 'Nutty sponge topped generously with roasted almond flakes for a crunchy, toasty finish.',
    image: require('../../assets/images/cake_chocolate_almond.jpg'), popular: false, sizes: [{ id: '2lb', label: '2 lb', price: 2800 }], addons: [] },
  { id: 's02', categoryId: 'specialty-cakes', name: 'Mixed Dry Fruit Cake', price: 2999,
    description: 'Traditional rich cake packed with a medley of dry fruits and nuts.',
    image: require('../../assets/images/cake_mixed_dry_fruit.jpg'), popular: false, sizes: [{ id: '2lb', label: '2 lb', price: 2999 }], addons: [] },
  { id: 's03', categoryId: 'specialty-cakes', name: 'Almond Dry Cake', price: 2600,
    description: 'A lighter, less-sweet almond cake perfect with a cup of tea or coffee.',
    image: '', popular: false, sizes: [{ id: '2lb', label: '2 lb', price: 2600 }], addons: [] },
  { id: 's04', categoryId: 'specialty-cakes', name: 'Black Forest Cake', price: 2400,
    description: 'Classic chocolate sponge layered with whipped cream, cherries and chocolate shavings.',
    image: '', popular: true, sizes: [{ id: '2lb', label: '2 lb', price: 2400 }], addons: [] },
  { id: 's05', categoryId: 'specialty-cakes', name: 'Pineapple Cake', price: 2400,
    description: 'Light vanilla sponge layered with fresh cream and juicy pineapple chunks.',
    image: require('../../assets/images/cake_pineapple.jpg'), popular: false, sizes: [{ id: '2lb', label: '2 lb', price: 2400 }], addons: [] },

  // ───────────────────────────── Classic Cakes (1.5 lb) ─────────────────────────
  { id: 'cl01', categoryId: 'classic-cakes', name: 'Plain Tea Cake', price: 550,
    description: 'A simple, lightly-sweet everyday cake — perfect alongside your evening tea.',
    image: '', popular: false, sizes: [{ id: '1.5lb', label: '1.5 lb', price: 550 }], addons: [] },
  { id: 'cl02', categoryId: 'classic-cakes', name: 'Marble Cake', price: 599,
    description: 'Vanilla and chocolate batter swirled together for a classic marbled look and flavor.',
    image: '', popular: false, sizes: [{ id: '1.5lb', label: '1.5 lb', price: 599 }], addons: [] },
  { id: 'cl03', categoryId: 'classic-cakes', name: 'Fruit Cake', price: 650,
    description: 'Soft sponge studded with candied and dried fruit for a homely, fragrant bite.',
    image: '', popular: false, sizes: [{ id: '1.5lb', label: '1.5 lb', price: 650 }], addons: [] },
  { id: 'cl04', categoryId: 'classic-cakes', name: 'Bento Cake', price: 1600,
    description: 'A cute, personal-sized mini cake — perfect for small celebrations or a solo treat.',
    image: '', popular: true, sizes: [{ id: '1.5lb', label: '1.5 lb', price: 1600 }], addons: [] },
  { id: 'cl05', categoryId: 'classic-cakes', name: 'Dream Cake (in a tin)', price: 1199,
    description: 'A moist, ready-to-gift cake baked and packed in its own tin.',
    image: '', popular: false, sizes: [{ id: '1.5lb', label: '1.5 lb', price: 1199 }], addons: [] },

  // ───────────────────────────── Savories ────────────────────────────────────────
  { id: 'sv01', categoryId: 'savories', name: 'Chicken Patties', price: 275,
    description: 'Flaky pastry parcels filled with a savory spiced chicken filling.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'sv02', categoryId: 'savories', name: 'Chicken & Potato Patties (1 pc)', price: 325,
    description: 'Hearty pastry filled with chicken and lightly spiced potato mash.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'sv03', categoryId: 'savories', name: 'Mini Pizza', price: 500,
    description: 'Bite-sized pizza topped with cheese and your favorite toppings, baked to a golden crisp.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'sv04', categoryId: 'savories', name: 'Chicken Bread', price: 499,
    description: 'Soft bread roll stuffed with a creamy, spiced chicken filling.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'sv05', categoryId: 'savories', name: 'Pizza Roll', price: 350,
    description: 'Rolled dough filled with pizza-style cheese and toppings, baked till golden.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'sv06', categoryId: 'savories', name: 'Chicken Quiche', price: 399,
    description: 'Buttery pastry shell filled with a savory chicken and egg custard.',
    image: '', popular: false, sizes: [], addons: [] },

  // ───────────────────────────── Pasta ───────────────────────────────────────────
  { id: 'pa01', categoryId: 'pasta', name: 'Lasagna', price: 1199,
    description: 'Layers of pasta, rich meat sauce and melted cheese baked to bubbling perfection.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'pa02', categoryId: 'pasta', name: 'Cheesy Pasta Bake', price: 1250,
    description: 'Baked pasta smothered in a creamy, cheesy sauce with a golden crust on top.',
    image: '', popular: false, sizes: [], addons: [] },

  // ───────────────────────────── Cold Sandwiches ─────────────────────────────────
  { id: 'sw01', categoryId: 'sandwiches', name: 'Grilled Chicken & Cheese Sandwich', price: 575,
    description: 'Grilled chicken and melted cheese between soft toasted bread.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'sw02', categoryId: 'sandwiches', name: 'Chicken Salad Sandwich', price: 550,
    description: 'Creamy chicken salad layered between fresh soft bread slices.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'sw03', categoryId: 'sandwiches', name: 'Plain Chicken Sandwich', price: 499,
    description: 'A simple, classic chicken sandwich — light and satisfying.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'sw04', categoryId: 'sandwiches', name: 'Club Sandwich', price: 999,
    description: 'Triple-decker sandwich loaded with chicken, egg, and fresh vegetables.',
    image: '', popular: true, sizes: [], addons: [] },

  // ───────────────────────────── Pastries & Eclairs ──────────────────────────────
  { id: 'pe01', categoryId: 'pastries-eclairs', name: 'Ferrero Bliss Pastry', price: 299,
    description: 'Chocolate-hazelnut pastry inspired by the beloved Ferrero praline flavor.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'pe02', categoryId: 'pastries-eclairs', name: 'Chocolate Pastry', price: 350,
    description: 'Soft sponge layered with chocolate cream and a smooth chocolate glaze.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'pe03', categoryId: 'pastries-eclairs', name: 'Caramel Crunch Pastry', price: 350,
    description: 'Layers of caramel cream and a crunchy praline topping over soft sponge.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'pe04', categoryId: 'pastries-eclairs', name: 'Chocolate Eclairs', price: 250,
    description: 'Classic choux pastry filled with cream and topped with rich chocolate glaze.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'pe05', categoryId: 'pastries-eclairs', name: 'Caramel Eclairs', price: 250,
    description: 'Choux pastry filled with vanilla cream and finished with a caramel glaze.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'pe06', categoryId: 'pastries-eclairs', name: 'Vanilla Swiss Roll', price: 350,
    description: 'Soft vanilla sponge rolled with a light, creamy vanilla filling.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'pe07', categoryId: 'pastries-eclairs', name: 'Chocolate Swiss Roll', price: 350,
    description: 'Chocolate sponge rolled around a smooth chocolate cream filling.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'pe08', categoryId: 'pastries-eclairs', name: 'Lemon Swiss Roll', price: 350,
    description: 'Light sponge rolled with a tangy, zesty lemon cream filling.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'pe09', categoryId: 'pastries-eclairs', name: 'Matilda Chocolate Heaven', price: 999,
    description: 'An indulgent multi-layer chocolate dessert built for serious chocolate lovers.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'pe10', categoryId: 'pastries-eclairs', name: 'Crème Brûlée', price: 550,
    description: 'Silky vanilla custard topped with a crisp, torched caramelized sugar crust.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'pe11', categoryId: 'pastries-eclairs', name: 'Tiramisu', price: 675,
    description: 'Espresso-soaked layers with a light mascarpone cream, dusted with cocoa.',
    image: require('../../assets/images/cake_tiramisu.jpg'), popular: true, sizes: [], addons: [] },
  { id: 'pe12', categoryId: 'pastries-eclairs', name: 'Macaroons (4 pcs)', price: 1299,
    description: 'A set of four delicate, colorful macaroon shells with a soft, chewy center.',
    image: '', popular: false, sizes: [], addons: [] },

  // ───────────────────────────── Salads ──────────────────────────────────────────
  { id: 'sl01', categoryId: 'salads', name: 'Chicken & Pasta Salad', price: 799,
    description: 'Grilled chicken tossed with pasta, fresh greens and a creamy dressing.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'sl02', categoryId: 'salads', name: 'Chicken Noodle Salad', price: 1299,
    description: 'Chilled noodles tossed with tender chicken and a light, tangy dressing.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'sl03', categoryId: 'salads', name: 'Chicken with Pineapple Salad', price: 1199,
    description: 'A refreshing mix of grilled chicken, sweet pineapple and crisp greens.',
    image: '', popular: false, sizes: [], addons: [] },

  // ───────────────────────────── Pie's & Tarts ───────────────────────────────────
  { id: 'pt01', categoryId: 'pies-tarts', name: 'Mini Apple Pie', price: 250,
    description: 'A bite-sized pie filled with cinnamon-spiced apple filling in a flaky crust.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'pt02', categoryId: 'pies-tarts', name: 'Mini Walnut Pie', price: 250,
    description: 'Buttery pastry filled with a sweet, sticky walnut filling.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'pt03', categoryId: 'pies-tarts', name: 'Mini Chocolate Tart', price: 350,
    description: 'A crisp tart shell filled with rich, silky chocolate ganache.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'pt04', categoryId: 'pies-tarts', name: 'Mini Lemon Tart', price: 299,
    description: 'Tangy lemon curd in a buttery tart shell — bright and refreshing.',
    image: '', popular: false, sizes: [], addons: [] },

  // ───────────────────────────── Bread & Croissant ───────────────────────────────
  { id: 'br01', categoryId: 'bread-croissant', name: 'Plain Croissant', price: 150,
    description: 'Flaky, buttery croissant baked fresh daily.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'br02', categoryId: 'bread-croissant', name: 'Danish Pastry', price: 350,
    description: 'Layered, flaky pastry with a soft, lightly sweet filling.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'br03', categoryId: 'bread-croissant', name: 'Milky Bread', price: 250,
    description: 'Soft, fluffy bread with a subtly sweet, milky flavor.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'br04', categoryId: 'bread-croissant', name: 'Multigrain Bread', price: 450,
    description: 'Hearty bread made with a wholesome blend of grains and seeds.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'br05', categoryId: 'bread-croissant', name: 'Sourdough Bread', price: 499,
    description: 'Naturally leavened bread with a tangy flavor and a crisp crust.',
    image: '', popular: false, sizes: [], addons: [] },

  // ───────────────────────────── Cupcakes ────────────────────────────────────────
  { id: 'cu01', categoryId: 'cupcakes', name: 'Chocolate Cupcake', price: 299,
    description: 'Moist chocolate cupcake topped with a swirl of chocolate frosting.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'cu02', categoryId: 'cupcakes', name: 'Chocolate Filled Cupcake', price: 350,
    description: 'Chocolate cupcake with a molten chocolate center and frosted top.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'cu03', categoryId: 'cupcakes', name: 'Lotus Cupcake', price: 299,
    description: 'Soft cupcake topped with creamy Lotus Biscoff frosting and crumble.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'cu04', categoryId: 'cupcakes', name: 'Ferrero Cupcake', price: 299,
    description: 'Chocolate-hazelnut cupcake topped with a Ferrero-inspired frosting.',
    image: '', popular: false, sizes: [], addons: [] },

  // ───────────────────────────── Brownies & Cookies ──────────────────────────────
  { id: 'bc01', categoryId: 'brownies-cookies', name: 'Chocolate Chip Cookie', price: 350,
    description: 'Classic chewy cookie loaded with chocolate chips.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'bc02', categoryId: 'brownies-cookies', name: 'Double Chocolate Cookie', price: 350,
    description: 'A rich chocolate cookie studded with extra chocolate chunks.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'bc03', categoryId: 'brownies-cookies', name: 'Fudge Brownie', price: 450,
    description: 'Dense, gooey chocolate brownie with a fudgy center.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'bc04', categoryId: 'brownies-cookies', name: 'Assorted Biscuits', price: 300,
    description: 'A mixed selection of freshly baked biscuits, sold per 100 grams.',
    image: '', popular: false, sizes: [{ id: '100g', label: '100 grams', price: 300 }], addons: [] },
  { id: 'bc05', categoryId: 'brownies-cookies', name: 'Milky Malt Brownies', price: 350,
    description: 'Soft brownies with a subtle malted-milk flavor twist.',
    image: '', popular: false, sizes: [], addons: [] },

  // ───────────────────────────── Donuts ──────────────────────────────────────────
  { id: 'do01', categoryId: 'donuts', name: 'Cadbury Donut', price: 250,
    description: 'Soft donut topped with a rich Cadbury chocolate glaze.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'do02', categoryId: 'donuts', name: 'Caramel Donut', price: 250,
    description: 'Fluffy donut drizzled with sweet caramel glaze.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'do03', categoryId: 'donuts', name: 'Caramel Chocolate Donut', price: 250,
    description: 'A donut topped with both chocolate and caramel glaze for double the flavor.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'do04', categoryId: 'donuts', name: 'Chocolate Filled Donut', price: 350,
    description: 'Soft donut filled with a rich chocolate cream center.',
    image: '', popular: false, sizes: [], addons: [] },

  // ───────────────────────────── Sundae's ────────────────────────────────────────
  { id: 'su01', categoryId: 'sundaes', name: 'Nutella Sundae', price: 499,
    description: 'Layers of ice cream drizzled with Nutella and toppings.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'su02', categoryId: 'sundaes', name: 'Lotus Sundae', price: 499,
    description: 'Creamy ice cream layered with Lotus Biscoff sauce and crumble.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'su03', categoryId: 'sundaes', name: 'Chocolate Mousse Cup', price: 499,
    description: 'Light, airy chocolate mousse served chilled in a cup.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'su04', categoryId: 'sundaes', name: 'Chocolate Sundae', price: 499,
    description: 'Classic ice cream sundae smothered in warm chocolate sauce.',
    image: '', popular: false, sizes: [], addons: [] },

  // ───────────────────────────── Muffins ─────────────────────────────────────────
  { id: 'mu01', categoryId: 'muffins', name: 'Vanilla Muffin', price: 350,
    description: 'Soft, fluffy muffin with a classic vanilla flavor.',
    image: '', popular: false, sizes: [], addons: [] },
  { id: 'mu02', categoryId: 'muffins', name: 'Chocolate Muffin', price: 350,
    description: 'Moist chocolate muffin studded with chocolate chips.',
    image: '', popular: true, sizes: [], addons: [] },
  { id: 'mu03', categoryId: 'muffins', name: 'Marble Muffin', price: 350,
    description: 'Vanilla and chocolate batter swirled together in a soft muffin.',
    image: '', popular: false, sizes: [], addons: [] },

  // ───────────────────────────── Hot Coffee ──────────────────────────────────────
  { id: 'hc01', categoryId: 'hot-coffee', name: 'Americano', price: 499,
    description: 'Espresso shots topped with hot water for a smooth, bold coffee.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 499 }, { id: 'lg', label: 'Large', price: 599 }],
    addons: [{ id: 'extra-shot', label: 'Extra Shot', price: 100 }] },
  { id: 'hc02', categoryId: 'hot-coffee', name: 'Cappuccino', price: 699,
    description: 'Espresso topped with steamed milk and a thick layer of micro-foam.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 699 }, { id: 'lg', label: 'Large', price: 899 }],
    addons: [{ id: 'extra-shot', label: 'Extra Shot', price: 100 }, { id: 'oat-milk', label: 'Oat Milk', price: 150 }] },
  { id: 'hc03', categoryId: 'hot-coffee', name: 'Café Latte', price: 699,
    description: 'Espresso balanced with steamed milk for a smooth, mellow cup.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 699 }, { id: 'lg', label: 'Large', price: 899 }],
    addons: [{ id: 'oat-milk', label: 'Oat Milk', price: 150 }] },
  { id: 'hc04', categoryId: 'hot-coffee', name: 'Flat White', price: 750,
    description: 'Concentrated espresso with velvety micro-foamed milk — strong and smooth.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 750 }, { id: 'lg', label: 'Large', price: 950 }], addons: [] },
  { id: 'hc05', categoryId: 'hot-coffee', name: 'Hazelnut Latte', price: 799,
    description: 'Classic latte sweetened with a rich hazelnut syrup.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 799 }, { id: 'lg', label: 'Large', price: 1075 }], addons: [] },
  { id: 'hc06', categoryId: 'hot-coffee', name: 'Caramel Latte', price: 799,
    description: 'Smooth espresso and steamed milk finished with a drizzle of caramel.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 799 }, { id: 'lg', label: 'Large', price: 1075 }], addons: [] },
  { id: 'hc07', categoryId: 'hot-coffee', name: 'Vanilla Latte', price: 799,
    description: 'Espresso and steamed milk sweetened with smooth vanilla syrup.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 799 }, { id: 'lg', label: 'Large', price: 1075 }], addons: [] },
  { id: 'hc08', categoryId: 'hot-coffee', name: 'Irish Latte', price: 799,
    description: 'A creamy latte flavored with a warm, sweet Irish cream syrup.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 799 }, { id: 'lg', label: 'Large', price: 1075 }], addons: [] },
  { id: 'hc09', categoryId: 'hot-coffee', name: 'Hafsum Cloud Latte', price: 799,
    description: "Hafsum's signature latte topped with a light, airy cloud of whipped foam.",
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 799 }, { id: 'lg', label: 'Large', price: 1075 }], addons: [] },
  { id: 'hc10', categoryId: 'hot-coffee', name: 'Hot Chocolate', price: 799,
    description: 'Rich, thick melted chocolate topped with a touch of cream.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 799 }, { id: 'lg', label: 'Large', price: 1099 }], addons: [] },
  { id: 'hc11', categoryId: 'hot-coffee', name: 'Spanish Latte', price: 875,
    description: 'Espresso blended with sweetened condensed milk for a creamy, rich cup.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 875 }, { id: 'lg', label: 'Large', price: 1175 }], addons: [] },
  { id: 'hc12', categoryId: 'hot-coffee', name: 'Café Mocha', price: 875,
    description: 'Espresso, chocolate and steamed milk combined for a chocolatey coffee treat.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 875 }, { id: 'lg', label: 'Large', price: 1175 }], addons: [] },
  { id: 'hc13', categoryId: 'hot-coffee', name: 'Cookie & Butter Latte', price: 899,
    description: 'A dessert-style latte flavored with sweet cookie-and-butter notes.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 899 }, { id: 'lg', label: 'Large', price: 1250 }], addons: [] },
  { id: 'hc14', categoryId: 'hot-coffee', name: 'Espresso', price: 425,
    description: 'Bold, concentrated espresso shot — pure and aromatic.',
    image: '', popular: false,
    sizes: [{ id: 'single', label: 'Single Shot', price: 425 }, { id: 'double', label: 'Double Shot', price: 525 }], addons: [] },
  { id: 'hc15', categoryId: 'hot-coffee', name: 'Macchiato', price: 499,
    description: 'Espresso "stained" with a small dollop of foamed milk.',
    image: '', popular: false,
    sizes: [{ id: 'single', label: 'Single Shot', price: 499 }, { id: 'double', label: 'Double Shot', price: 599 }], addons: [] },

  // ───────────────────────────── Cold Coffee ─────────────────────────────────────
  { id: 'cc01', categoryId: 'cold-coffee', name: 'Iced Americano', price: 699,
    description: 'Chilled espresso over ice with cold water — crisp and refreshing.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 699 }, { id: 'lg', label: 'Large', price: 899 }], addons: [] },
  { id: 'cc02', categoryId: 'cold-coffee', name: 'Iced Latte', price: 950,
    description: 'Chilled espresso and cold milk served over ice.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 950 }, { id: 'lg', label: 'Large', price: 1175 }], addons: [] },
  { id: 'cc03', categoryId: 'cold-coffee', name: 'Coconut Iced Americano', price: 1099,
    description: 'Fan-favorite iced americano blended with creamy coconut milk.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 1099 }, { id: 'lg', label: 'Large', price: 1299 }], addons: [] },
  { id: 'cc04', categoryId: 'cold-coffee', name: 'Iced Hazelnut Latte', price: 1175,
    description: 'Cold espresso and milk sweetened with hazelnut syrup over ice.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 1175 }, { id: 'lg', label: 'Large', price: 1375 }], addons: [] },
  { id: 'cc05', categoryId: 'cold-coffee', name: 'Iced Vanilla Latte', price: 1175,
    description: 'Chilled espresso and milk with smooth vanilla sweetness.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 1175 }, { id: 'lg', label: 'Large', price: 1375 }], addons: [] },
  { id: 'cc06', categoryId: 'cold-coffee', name: 'Iced Caramel Latte', price: 1175,
    description: 'Cold espresso and milk finished with a generous caramel drizzle.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 1175 }, { id: 'lg', label: 'Large', price: 1375 }], addons: [] },
  { id: 'cc07', categoryId: 'cold-coffee', name: 'Iced Spanish Latte', price: 1175,
    description: 'Chilled espresso with sweetened condensed milk — a fan favorite.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 1175 }, { id: 'lg', label: 'Large', price: 1375 }], addons: [] },
  { id: 'cc08', categoryId: 'cold-coffee', name: 'Iced Irish Latte', price: 1175,
    description: 'Cold latte flavored with a sweet, creamy Irish cream syrup.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 1175 }, { id: 'lg', label: 'Large', price: 1375 }], addons: [] },
  { id: 'cc09', categoryId: 'cold-coffee', name: 'Iced Mocha Latte', price: 1175,
    description: 'Chilled espresso, chocolate and milk poured over ice.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 1175 }, { id: 'lg', label: 'Large', price: 1375 }], addons: [] },
  { id: 'cc10', categoryId: 'cold-coffee', name: 'Blended Cold Coffee', price: 1250,
    description: 'Coffee blended with ice into a thick, frappé-style drink.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 1250 }, { id: 'lg', label: 'Large', price: 1450 }], addons: [] },
  { id: 'cc11', categoryId: 'cold-coffee', name: 'Lotus Iced Latte', price: 1250,
    description: 'Iced latte infused with creamy Lotus Biscoff flavor.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 1250 }, { id: 'lg', label: 'Large', price: 1450 }], addons: [] },

  // ───────────────────────────── Mojitos ─────────────────────────────────────────
  { id: 'mj01', categoryId: 'mojitos', name: 'Classic Mint Mojito', price: 499,
    description: 'Refreshing blend of fresh mint, lime and soda over ice.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 499 }, { id: 'lg', label: 'Large', price: 699 }], addons: [] },
  { id: 'mj02', categoryId: 'mojitos', name: 'Blue Lagoon Mojito', price: 750,
    description: 'A vibrant blue mocktail with citrus and mint over crushed ice.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 750 }, { id: 'lg', label: 'Large', price: 950 }], addons: [] },
  { id: 'mj03', categoryId: 'mojitos', name: 'Coconut Mojito', price: 750,
    description: 'Mint and lime mojito given a tropical twist with coconut.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 750 }, { id: 'lg', label: 'Large', price: 950 }], addons: [] },
  { id: 'mj04', categoryId: 'mojitos', name: 'Peach Mojito', price: 750,
    description: 'Sweet peach flavor combined with fresh mint and lime.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 750 }, { id: 'lg', label: 'Large', price: 950 }], addons: [] },
  { id: 'mj05', categoryId: 'mojitos', name: 'Strawberry Mojito', price: 750,
    description: 'Fresh strawberry puree blended with mint and lime over ice.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 750 }, { id: 'lg', label: 'Large', price: 950 }], addons: [] },
  { id: 'mj06', categoryId: 'mojitos', name: 'Passion Berry Mojito', price: 850,
    description: 'Tropical passion fruit and mixed berries with fresh mint and lime.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 850 }, { id: 'lg', label: 'Large', price: 1150 }], addons: [] },

  // ───────────────────────────── Lemonades ───────────────────────────────────────
  { id: 'lm01', categoryId: 'lemonades', name: 'Classic Lemonade', price: 599,
    description: 'Freshly squeezed lemon juice, lightly sweetened and chilled.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 599 }, { id: 'lg', label: 'Large', price: 799 }], addons: [] },
  { id: 'lm02', categoryId: 'lemonades', name: 'Mint Lemonade', price: 599,
    description: 'Classic lemonade infused with fresh mint for extra refreshment.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 599 }, { id: 'lg', label: 'Large', price: 799 }], addons: [] },
  { id: 'lm03', categoryId: 'lemonades', name: 'Strawberry Lemonade', price: 599,
    description: 'Lemonade blended with sweet strawberry puree.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 599 }, { id: 'lg', label: 'Large', price: 799 }], addons: [] },

  // ───────────────────────────── Iced Teas ───────────────────────────────────────
  { id: 'it01', categoryId: 'iced-teas', name: 'Peach Iced Tea', price: 799,
    description: 'Chilled black tea infused with sweet peach flavor.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 799 }, { id: 'lg', label: 'Large', price: 999 }], addons: [] },
  { id: 'it02', categoryId: 'iced-teas', name: 'Lemon Iced Tea', price: 799,
    description: 'Classic chilled iced tea with a bright, citrusy lemon finish.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 799 }, { id: 'lg', label: 'Large', price: 999 }], addons: [] },
  { id: 'it03', categoryId: 'iced-teas', name: 'Pomegranate Iced Tea', price: 799,
    description: 'Chilled iced tea infused with tart, fruity pomegranate.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 799 }, { id: 'lg', label: 'Large', price: 999 }], addons: [] },

  // ───────────────────────────── Mocktails ───────────────────────────────────────
  { id: 'mo01', categoryId: 'mocktails', name: 'Mint Margarita', price: 499,
    description: 'A zesty citrus and mint mocktail served over crushed ice.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 499 }, { id: 'lg', label: 'Large', price: 699 }], addons: [] },
  { id: 'mo02', categoryId: 'mocktails', name: 'Shirley Temple', price: 725,
    description: 'A classic sweet mocktail of ginger ale, grenadine and a cherry garnish.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 725 }, { id: 'lg', label: 'Large', price: 925 }], addons: [] },
  { id: 'mo03', categoryId: 'mocktails', name: 'Strawberry Mimosa', price: 725,
    description: 'A fruity, bubbly mocktail with fresh strawberry puree.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 725 }, { id: 'lg', label: 'Large', price: 925 }], addons: [] },
  { id: 'mo04', categoryId: 'mocktails', name: 'Peach & Pineapple', price: 825,
    description: 'Tropical blend of sweet peach and pineapple flavors.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 825 }, { id: 'lg', label: 'Large', price: 1050 }], addons: [] },
  { id: 'mo05', categoryId: 'mocktails', name: 'Shark Bite', price: 825,
    description: 'A fun, fruity layered mocktail with a bold tropical punch.',
    image: '', popular: true,
    sizes: [{ id: 'reg', label: 'Regular', price: 825 }, { id: 'lg', label: 'Large', price: 1050 }], addons: [] },
  { id: 'mo06', categoryId: 'mocktails', name: 'Pina Colada', price: 925,
    description: 'Creamy coconut and pineapple blended together for a tropical classic.',
    image: '', popular: false,
    sizes: [{ id: 'reg', label: 'Regular', price: 925 }, { id: 'lg', label: 'Large', price: 1125 }], addons: [] },
];

// ─── Promo Banners ────────────────────────────────────────────────────────────
export const BANNERS = [
  {
    id: 'b1',
    title: 'Now Open',
    subtitle: 'Best Western\nRawalpindi Central',
    cta: 'Order Now',
    bg: '#2E1540',
    image: '',
  },
  {
    id: 'b2',
    title: 'Sweet Moments',
    subtitle: 'Perfectly Brewed\nCoffee & Cake',
    cta: 'Explore Menu',
    bg: '#3A2010',
    image: '',
  },
  {
    id: 'b3',
    title: 'Fan Favorite',
    subtitle: 'Coconut Iced\nAmericano ★',
    cta: 'Try Now',
    bg: '#1A3A2A',
    image: '',
  },
];

// ─── Mock Orders ──────────────────────────────────────────────────────────────
export const MOCK_ORDERS = [
  {
    id: 'HFS-10241',
    date: '2026-08-10T08:30:00Z',
    status: 'completed',
    items: [
      { name: 'Cappuccino', qty: 2, price: 699 },
      { name: 'Chocolate Fudge Cake', qty: 1, price: 1999 },
    ],
    subtotal: 3397,
    deliveryFee: 150,
    total: 3547,
    type: 'delivery',
    address: 'Commercial Avenue, Sector A, Bahria Enclave, Islamabad',
  },
  {
    id: 'HFS-10242',
    date: '2026-08-11T10:00:00Z',
    status: 'preparing',
    items: [
      { name: 'Caramel Latte', qty: 1, price: 799 },
      { name: 'Plain Croissant', qty: 2, price: 150 },
    ],
    subtotal: 1099,
    deliveryFee: 0,
    total: 1099,
    type: 'pickup',
    address: '',
  },
];

// ─── Branches ─────────────────────────────────────────────────────────────────
export const BRANCHES = [
  {
    id: 'br1',
    name: 'Hafsum – Bahria Enclave, Islamabad',
    address: 'Commercial Avenue, Sector A, Bahria Enclave, Islamabad',
    hours: 'Mon–Sun  07:00 – 23:00',
    phone: '051-8482320 / 0333-6276667',
    pickup: true,
  },
  {
    id: 'br2',
    name: 'Hafsum – Best Western, Bahria Town Rawalpindi',
    address: 'Best Western, Phase 4, Bahria Town, Rawalpindi',
    hours: 'Mon–Sun  07:00 – 23:00',
    phone: '051-8442118 / 0331-5236688',
    pickup: true,
  },
];